import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Compnents/Header/Header";
import { APIProvider } from "@/context/MyContext";
import Footer from "@/Compnents/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <APIProvider>
        <div className="pageMain">
          <div className="pageInner">
            <div>
              <Header />
              {children}
              <Footer/>
            </div>
          </div>
        </div>
        </APIProvider>
      </body>
    </html>
  );
}
